name: test-setup-eksctl

on:
  pull_request:
    branches:
      - main
    paths:
      - 'setup-eksctl/**'
      - '.github/workflows/test-setup-eksctl.yaml'

permissions: {}

jobs:
  test-github-action:
    name: test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      # install an old version, and check that we got the expected version
      - uses: "./setup-eksctl"
        with:
          version: "v0.209.0"

      - name: verify version
        shell: bash
        run: |
          out=$(/usr/local/bin/eksctl info) || {
            echo "FATAL: execution of /usr/local/bin/eksctl failed $?"
            exit 1
          }

          expected=0.209.0
          found=$(echo "$out" | awk '$0 ~ /^eksctl version:/ { printf("%s\n", $3); }')
          [ "$found" = "$expected" ] || {
            echo "FATAL: expected version '$expected'. found '$found'"
            exit 1
          }
          echo "verified version $expected was installed"

      - uses: "./setup-eksctl"

      # install latest (no 'release' input needed) and check that
      # we have a version other than the one above.
      - name: verify latest
        shell: bash
        run: |
          out=$(/usr/local/bin/eksctl info) || {
            echo "FATAL: execution of /usr/local/bin/eksctl failed $?"
            exit 1
          }

          ver=$(echo "$out" | awk '$0 ~ /^eksctl version:/ { printf("%s\n", $3); }')
          [ "$ver" != "0.209.0" ]

          echo "installed eksctl version = $ver"
          eksctl info
